add video caputurer project
opentok/opentok-ios-sdk-samples pull request #232
Opened 2020-10-16 16:30 UTC by abdulajet

Similar story to #231 

The dev centre page in question is https://tokbox.com/developer/tutorials/ios/custom-camera-video-capturing/
And the additional classes on top of the basic video project are `OTKBasicVideoCapturer` and `OTKBasicVideoCapturerCamera`

2020-11-16 02:38 UTC, jeffswartz requested changes

2020-11-16 02:38 UTC, jeffswartz commented on Basic-Video-Capturer/README.md
> +The Basic Video Capturer is a sample application showing to make modifications to the video capturer in your OpenTok iOS application. For a full description, see the [Video capturer tutorial at the
```suggestion
The Basic Video Capturer is a sample application showing how to make modifications to the video capturer
in your OpenTok iOS application. For a full description, see the [Video capturer tutorial at the
```

2020-11-16 06:42 UTC, jeffswartz requested changes

2020-11-16 06:42 UTC, jeffswartz commented on Basic-Video-Capturer/Basic-Video-Chat/ViewController.m
> + * NB: You do *not* have to call unsubscribe in your controller in response to
NB may be a bit confusing for some of us. ;)

2020-11-16 11:05 UTC, abdulajet commented on Basic-Video-Capturer/Basic-Video-Chat/ViewController.m
> + * NB: You do *not* have to call unsubscribe in your controller in response to
```suggestion
 * Note: You do *not* have to call unsubscribe in your controller in response to
```

2021-03-05 07:58 UTC, jeffswartz approved these changes

2024-09-23 12:19 UTC, closed without merging